использовал хуки
htmlacademy-react/1138711-six-cities-6 pull request #5
Opened 2021-02-13 09:17 UTC by Yougn

2021-02-13 10:18 UTC, balesniy requested changes

2021-02-13 10:18 UTC, balesniy commented on src/components/favorites/favorites-card/favorites-card.jsx
> +            <span style={{width: `80%`}}></span>
ширину нужно посчитать от рейтинга

2021-02-13 10:18 UTC, balesniy commented on src/components/favorites/favorites-card/favorites-card.jsx
> +        <p className="place-card__type" id={id}>{type}</p>
на странице не может быть двух элементов с одинаковым id

2021-02-13 10:18 UTC, balesniy commented on src/components/favorites/favorites.jsx
>          <section className="favorites">
карточки нужно распределить по городам

2021-02-13 10:18 UTC, balesniy commented on src/components/place-card/place-card.jsx
> +    <article className="cities__place-card place-card" onMouseEnter ={mouseEnterIdHandler} id={id}>
id на странице должен быть уникальным

2021-02-13 10:18 UTC, balesniy commented on src/components/place-card/place-card.jsx
>          <a href="#">
Используя компонент Link из пакета react-router-dom

2021-02-13 10:18 UTC, balesniy commented on src/components/place-card/place-card.jsx
> +          <button className="place-card__bookmark-button button" type="button" id={id} onClick={() => history.push(`/favorites`)}>
клик на кнопку не должен приводить к переходу

2021-02-13 10:18 UTC, balesniy commented on src/components/place-card/place-card.jsx
> +              <svg className="place-card__bookmark-icon" width="18" height="19"><use xlinkHref="#icon-bookmark"></use></svg>}
одинаковый код в ветках

2021-02-13 10:18 UTC, balesniy commented on src/components/place-card/place-card.jsx
> +        <h2 className="place-card__name" onClick={() => history.push(`/offer/:id`)}>
Используя компонент Link из пакета react-router-dom - в адресе нужно указать id, `/offer/:id` это шаблон для роутера, а тут нужен заполненный url

2021-02-13 10:18 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +  let onTextChange = (evt) => {
const

2021-02-13 10:18 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +  const {review} = props;
https://up.htmlacademy.ru/react/6/criteries#b10

2021-02-13 10:18 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +        <input className="form__rating-input visually-hidden" name="rating" value="5" id="5-stars" type="radio" />
Реализуйте сохранение введённых в форму данных в state компонента.

2021-02-13 10:18 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +        <input className="form__rating-input visually-hidden" name="rating" value="4" id="4-stars" type="radio" />
однотипную разметку лучше реализовать в цикле

2021-02-13 10:18 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +      <textarea className="reviews__textarea form__textarea" onChange={onTextChange} value={comment} id="review" name="review" placeholder="Tell how was your stay, what you like and what can be impro
value={userReview}

2021-02-13 10:18 UTC, balesniy commented on src/components/room/room.jsx
>                <span className="property__rating-value rating__value">4.8</span>
рейтинг нужно взять из моков

2021-02-13 10:18 UTC, balesniy commented on src/components/room/room.jsx
>                    <div className="reviews__info">
ревью нужно взять из моков

2021-02-13 10:18 UTC, balesniy commented on src/components/room/room.jsx
>                  <div className="place-card__rating rating">
соседние места нужно взять из моков, компонент карточки места можно переиспользовать

2021-02-13 10:18 UTC, balesniy commented on src/index.js
> +      review={review}
это лишнее

2021-02-13 12:58 UTC, Yougn commented on src/components/app/app.jsx
> +  offers: PropTypes.array.isRequired,
Исправлено

2021-02-13 13:05 UTC, Yougn commented on src/components/cards-list/cards-list.jsx
> +  const mouseEnterCardId = (cardId)=> {
Исправлено

2021-02-13 13:13 UTC, Yougn commented on src/components/cards-list/cards-list.jsx
> +  const offerCards = offers.map((offer) => <PlaceCard key={offer.id} offer={offer} mouseEnterCardId={mouseEnterCardId} />);
Исправлено

2021-02-13 13:16 UTC, Yougn commented on src/components/cards-list/cards-list.jsx
> +  offers: PropTypes.array.isRequired
Исправлено

2021-02-13 13:17 UTC, Yougn commented on src/components/cards-list/cards-list.jsx
> +  offers: PropTypes.array.isRequired
Исправлено

2021-02-13 13:42 UTC, Yougn commented on src/components/favorites/favorites-card/favorites-card.jsx
> +            <span style={{width: `80%`}}></span>
Исправлено

2021-02-13 13:53 UTC, Yougn commented on src/components/favorites/favorites-card/favorites-card.jsx
> +        <p className="place-card__type" id={id}>{type}</p>
Исправлено

2021-02-13 13:59 UTC, Yougn commented on src/components/place-card/place-card.jsx
> +    <article className="cities__place-card place-card" onMouseEnter ={mouseEnterIdHandler} id={id}>
Исправлено

2021-02-13 16:29 UTC, Yougn commented on src/components/favorites/favorites-card/favorites-card.jsx
> +            { isFavorite ?
Исправлено

2021-02-13 16:31 UTC, Yougn commented on src/components/place-card/place-card.jsx
> +          <button className="place-card__bookmark-button button" type="button" id={id} onClick={() => history.push(`/favorites`)}>
Исправлено

2021-02-13 16:33 UTC, Yougn commented on src/components/place-card/place-card.jsx
>          <a href="#">
Исправлено

2021-02-13 16:37 UTC, Yougn commented on src/components/place-card/place-card.jsx
> +              <svg className="place-card__bookmark-icon" width="18" height="19"><use xlinkHref="#icon-bookmark"></use></svg>}
Исправил.

2021-02-13 16:44 UTC, Yougn commented on src/components/place-card/place-card.jsx
> +        <h2 className="place-card__name" onClick={() => history.push(`/offer/:id`)}>
Исправлено

2021-02-13 16:44 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +  let onTextChange = (evt) => {
Исправлено

2021-02-13 16:48 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +  const {review} = props;
Исправлено

2021-02-13 16:51 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +      <textarea className="reviews__textarea form__textarea" onChange={onTextChange} value={comment} id="review" name="review" placeholder="Tell how was your stay, what you like and what can be impro
Исправлено

2021-02-13 16:51 UTC, Yougn commented on src/components/room/room.jsx
>                <span className="property__rating-value rating__value">4.8</span>
Исправлено

2021-02-14 11:45 UTC, Yougn commented on src/components/favorites/favorites.jsx
>          <section className="favorites">
Исправлено

2021-02-14 13:33 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +        <input className="form__rating-input visually-hidden" name="rating" value="4" id="4-stars" type="radio" />
Исправлено

2021-02-14 15:44 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +        <input className="form__rating-input visually-hidden" name="rating" value="5" id="5-stars" type="radio" />
Исправлено

2021-02-14 16:33 UTC, Yougn commented on src/components/room/room.jsx
>                    <div className="reviews__info">
Исправлено

2021-02-14 16:35 UTC, Yougn commented on src/index.js
> +      review={review}
Исправлено

2021-02-14 20:30 UTC, balesniy requested changes

2021-02-14 20:30 UTC, balesniy commented on src/components/app/app.jsx
> +          <Favorites offers={offers} />
в этот компонент нужно передать только избранные объявления

2021-02-14 20:30 UTC, balesniy commented on src/components/app/app.jsx
> +          <Room offers={offers} reviews={reviews}/>
а в этот одно объявление по id и ближайшие к нему

2021-02-14 20:30 UTC, balesniy commented on src/components/cards-list/cards-list.jsx
> +  const onMouseEnterCardId = (cardId)=> {
https://up.htmlacademy.ru/react/6/criteries#d2

2021-02-14 20:30 UTC, balesniy commented on src/components/favorites/favorite-card/favorite-card.jsx
> +          <a href="#">{title}</a>
Используя компонент Link из пакета react-router-dom свяжите страницы приложения. Например, клик по заголовку карточки предложения должен переводить пользователя на страницу «Room» с подробным описанием предложения по аренде.

2021-02-14 20:30 UTC, balesniy commented on src/components/favorites/favorites.jsx
> +  const locations = cityNames.map((name) => <FavoriteLocation key={name} name={name} offers={totalPlaceCards.filter((placeCard) => placeCard.city === name)} />);
лишний фильтр, в cardsGroups уже собраны объекты по городам

2021-02-14 20:30 UTC, balesniy commented on src/components/place-card/place-card.jsx
> +        <h2 className="place-card__name" onClick={() => history.push(`/offer/:` + id)}>
тут надо что-то одно применить, для ссылок лучше LInk

2021-02-14 20:30 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +    let text = evt.target.value;
const

2021-02-14 20:30 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +  const onTextChange = (evt) => {
Д2

2021-02-14 20:30 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +    let choiseId = evt.target.id;
const

2021-02-14 20:30 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +  const onChoiseChange = (evt) => {
handle

2021-02-14 20:30 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +  const numbers = [...Array(STARS_COUNT)].map((_, i) => i - STARS_COUNT);
получился массив чисел по возрастанию, а в разметке они нужны по-убыванию, и в стейт приходит отрицательное значение

2021-02-14 20:30 UTC, balesniy commented on src/components/room/near-room/near-room.jsx
> +        <h2 className="place-card__name" onClick={() => history.push(`/offer/:` + id)}>
history.push лишний, компонент карточки можно переиспользовать

2021-02-14 20:30 UTC, balesniy commented on src/components/room/room.jsx
> +  const {comment, date, rating} = reviews[0];
тут нужно показать список комментариев к данному объекту, отобрать подходящие

2021-02-14 20:30 UTC, balesniy commented on src/components/room/room.jsx
> +              <img className="property__image" src="img/apartment-01.jpg" alt="Photo studio" />
фото нужно взять из объекта с данными

2021-02-14 20:30 UTC, balesniy commented on src/components/room/room.jsx
> +              <span>Premium</span>
шаблон нужно заполнить из объекта с данными

2021-02-14 20:30 UTC, balesniy commented on src/components/room/room.jsx
>                <span className="property__rating-value rating__value">4.8</span>
все еще нужно исправить

2021-02-14 20:30 UTC, balesniy commented on src/components/room/room.jsx
>                    <div className="reviews__info">
нужно исправить

2021-02-14 20:30 UTC, balesniy commented on src/components/room/room.jsx
> +              { <ReviewsForm reviews={reviews} />}
лишние скобки и пропс не объявлен в компоненте ReviewsForm

2021-02-15 09:30 UTC, Yougn commented on src/components/room/room.jsx
>                <span className="property__rating-value rating__value">4.8</span>
Исправлено

2021-02-15 09:43 UTC, Yougn commented on src/components/room/room.jsx
>                    <div className="reviews__info">
Исправлено - добавил моковые данные

2021-02-15 09:44 UTC, Yougn commented on src/components/room/room.jsx
>                  <div className="place-card__rating rating">
Исправлено

2021-02-15 09:53 UTC, Yougn commented on src/common/utils.js
> +const RATING_STEP = 20;
Исправлено

2021-02-15 10:03 UTC, Yougn commented on src/components/app/app.jsx
> +          <Favorites offers={offers} />
Исправлено

2021-02-15 10:30 UTC, Yougn commented on src/components/cards-list/cards-list.jsx
> +  const onMouseEnterCardId = (cardId)=> {
в критерии говорится о методе обработчика класса, а здесь создаю колбек функциональной компоненты и перадaю его в другую компоненту,  и уже там использую handle  при событии наведения на объект

2021-02-15 10:32 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +    let text = evt.target.value;
Исправлено

2021-02-15 10:34 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +  const onTextChange = (evt) => {
Исправлено

2021-02-15 10:34 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +    let choiseId = evt.target.id;
Исправлено

2021-02-15 10:36 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +  const onChoiseChange = (evt) => {
Исправлено

2021-02-15 13:20 UTC, Yougn commented on src/components/favorites/favorites.jsx
> +  const locations = cityNames.map((name) => <FavoriteLocation key={name} name={name} offers={totalPlaceCards.filter((placeCard) => placeCard.city === name)} />);
Исправлено

2021-02-15 13:24 UTC, Yougn commented on src/components/app/app.jsx
> +          <Room offers={offers} reviews={reviews}/>
паттерн render будет на сегодняшней лекции, поэтому захардкодил

2021-02-15 13:29 UTC, Yougn commented on src/components/favorites/favorite-card/favorite-card.jsx
> +          <a href="#">{title}</a>
Исправлено

2021-02-15 13:35 UTC, Yougn commented on src/components/place-card/place-card.jsx
> +        <h2 className="place-card__name" onClick={() => history.push(`/offer/:` + id)}>
Исправлено

2021-02-15 13:40 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +  const numbers = [...Array(STARS_COUNT)].map((_, i) => i - STARS_COUNT);
Исправлено. Не понял зачем нужен массив чисел по убыванию, ведь по возрастанию логичней: 1 звездочка соответствует id с номером 1

2021-02-15 13:48 UTC, Yougn commented on src/components/room/near-room/near-room.jsx
> +        <h2 className="place-card__name" onClick={() => history.push(`/offer/:` + id)}>
Исправлено. Из-за особенностей некоторых классов  пришлось бы изменять уже существующий компонент place-card и выделять дополнительный, поэтому решил сделать отдельный компонент для комнат

2021-02-15 14:05 UTC, Yougn commented on src/components/room/room.jsx
> +              { <ReviewsForm reviews={reviews} />}
Исправлено

2021-02-15 14:21 UTC, Yougn commented on src/components/room/room.jsx
> +  const {comment, date, rating} = reviews[0];
Исправлено., но пока захардкодил

2021-02-15 14:25 UTC, balesniy commented on src/components/app/app.jsx
> +          <Room offers={offers} reviews={reviews}/>
от паттерна спецификация компонента не изменится, в компонент нужно передавать только те данные, которые нужны для его отрисовки, список всех предложений для отрисовки отдельного точно избыточен, а списка ближайших не хватает

2021-02-15 14:28 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +  const numbers = [...Array(STARS_COUNT)].map((_, i) => i - STARS_COUNT);
массив чисел по убыванию не нужен, нужен обратный порядок в разметке - https://github.com/htmlacademy-react/1138711-six-cities-6/blob/master/markup/property.html#L182

2021-02-15 14:29 UTC, Yougn commented on src/components/room/room.jsx
> +              <span>Premium</span>
Исправлено

2021-02-15 14:40 UTC, Yougn commented on src/components/room/room.jsx
> +              <img className="property__image" src="img/apartment-01.jpg" alt="Photo studio" />
Исправлено

2021-02-15 21:33 UTC, balesniy requested changes
все еще нужно поправить пропсы компонентов и заполнить шаблоны, жду исправлений в следующей ветке

2021-02-15 21:33 UTC, balesniy commented on src/components/app/app.jsx
> +          <Room offers={offers} reviews={reviews}/>
в компонент нужно передать один объект с данными и отдельно список предложений неподалеку

2021-02-15 21:33 UTC, balesniy commented on src/components/favorites/favorite-card/favorite-card.jsx
> +          <Link to={`/offer/:` + id}>{title}</Link>
в url двоеточие не используется, оно нужно только для роутера чтобы показать что в строке будет параметр

2021-02-15 21:33 UTC, balesniy commented on src/components/place-card/place-card.jsx
> +  offer: PropTypes.shape(propCard),
isRequired

2021-02-15 21:33 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +  const {reviews} = props;
'reviews' is missing in props validation - лишний

2021-02-15 21:33 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +        {numbers.map((number)=> <Star key={number} id={number} userChoise={userChoise} handleInputChange={handleInputChange} />)}
колбэки в пропс нужно назвать через on

2021-02-15 21:33 UTC, balesniy commented on src/components/reviews-form/star/star.jsx
> +      <label htmlFor={id} className="reviews__rating-label form__rating-label" title="perfect">
порядок звездочек все еще не соответствует разметке

2021-02-15 21:33 UTC, balesniy commented on src/components/reviews-form/star/star.jsx
> +      <input className="form__rating-input visually-hidden" name="rating" value={userChoise} onChange={handleInputChange} id={id} type="radio" />
у радио-инпутов нужно проставить checked от userChoise

2021-02-15 21:33 UTC, balesniy commented on src/components/room/comment/comment.jsx
> +  const {comment, date, rating, user} = reviews[0];
в компонент нужно передать один отзыв

2021-02-15 21:33 UTC, balesniy commented on src/components/room/comment/comment.jsx
> +        <time className="reviews__time" dateTime="2019-04-24">{date}</time>
dateTime нужно заполнить

2021-02-15 21:33 UTC, balesniy commented on src/components/room/room-photo/room-photo.jsx
> +      <img className="property__image" src="img/apartment-01.jpg" alt="Photo studio" />
адрес картинки нужно передать в пропс

2021-02-15 21:33 UTC, balesniy commented on src/components/room/room.jsx
> +              <img className="property__image" src="img/apartment-01.jpg" alt="Photo studio" />
все еще нужно исправить

2021-02-15 21:33 UTC, balesniy commented on src/components/room/room.jsx
> +                3 Bedrooms
берем из данных

2021-02-15 21:33 UTC, balesniy commented on src/components/room/room.jsx
> +                  Wi-Fi
берем из данных

2021-02-15 21:33 UTC, balesniy commented on src/components/room/room.jsx
> +                  Angelina
берем из данных

2021-02-15 21:33 UTC, balesniy commented on src/components/room/room.jsx
> +              <ul className="reviews__list">
тут ожидается список комментов

2021-02-15 21:34 UTC, merged

2021-02-16 18:18 UTC, Yougn commented on src/components/favorites/favorite-card/favorite-card.jsx
> +          <Link to={`/offer/:` + id}>{title}</Link>
Исправлено

2021-02-16 18:19 UTC, Yougn commented on src/components/place-card/place-card.jsx
> +  offer: PropTypes.shape(propCard),
Исправлено

2021-02-16 18:21 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +  const {reviews} = props;
Исправлено

2021-02-16 18:41 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +        {numbers.map((number)=> <Star key={number} id={number} userChoise={userChoise} handleInputChange={handleInputChange} />)}
Исправлено. Где-то оставил handler как напоминание, чтобы функциональную компоненту в классовую переписать

2021-02-16 18:46 UTC, Yougn commented on src/components/reviews-form/star/star.jsx
> +      <label htmlFor={id} className="reviews__rating-label form__rating-label" title="perfect">
Исправлено

2021-02-17 10:12 UTC, Yougn commented on src/components/reviews-form/star/star.jsx
> +      <input className="form__rating-input visually-hidden" name="rating" value={userChoise} onChange={handleInputChange} id={id} type="radio" />
Исправлено

2021-02-17 10:45 UTC, Yougn commented on src/components/room/room-photo/room-photo.jsx
> +      <img className="property__image" src="img/apartment-01.jpg" alt="Photo studio" />
Исправлено

2021-02-17 10:49 UTC, Yougn commented on src/components/room/room.jsx
> +                3 Bedrooms
Исправлено

2021-02-17 11:13 UTC, Yougn commented on src/components/room/room.jsx
> +                  Wi-Fi
Исправлено

2021-02-17 11:17 UTC, Yougn commented on src/components/room/room.jsx
> +                  Angelina
Исправлено

2021-02-17 12:14 UTC, Yougn commented on src/components/room/comment/comment.jsx
> +  const {comment, date, rating, user} = reviews[0];
Исправлено

2021-02-17 12:22 UTC, Yougn commented on src/components/room/room.jsx
> +              <ul className="reviews__list">
Исправлено

2021-02-17 12:22 UTC, Yougn commented on src/components/room/comment/comment.jsx
> +        <time className="reviews__time" dateTime="2019-04-24">{date}</time>
Исправлено