внес правки
htmlacademy-react/1138711-six-cities-6 pull request #6
Opened 2021-02-17 12:49 UTC by Yougn

2021-02-17 14:17 UTC, balesniy requested changes

2021-02-17 14:17 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +  const onInputChange = (evt) => {
обработчики просят называть через handle, а props через on

2021-02-17 14:17 UTC, balesniy commented on src/components/reviews-form/reviews-form.jsx
> +        {numbers.map((number)=> <Star key={number} id={number} userChoise={userChoise} onInputChange={onInputChange} />)}
onInputChange={handleInputChange}

2021-02-17 14:17 UTC, balesniy commented on src/components/room/near-room/near-room.jsx
> +  nearOffer: PropTypes.shape(propCard)
isRequired

2021-02-17 14:17 UTC, balesniy commented on src/components/room/property-inside/property-inside.jsx
> +const PropertyInside = (props) => {
компонент выглядит избыточным, он добавляет один элемент

2021-02-17 14:17 UTC, balesniy commented on src/components/room/room.jsx
> +            <RoomPhoto img={img} />
в объявлении будет массив фоток, нужно его отрисовать, посмотри пример в markup

2021-02-17 14:17 UTC, balesniy commented on src/components/room/room.jsx
>          <div className="property__container container">
для Premium нужно добавить условие

2021-02-17 14:17 UTC, balesniy commented on src/components/room/room.jsx
>                    <img className="property__avatar user__avatar" src="img/avatar-angelina.jpg" width="74" height="74" alt="Host avatar" />
аватарка тоже придет в данных

2021-02-17 14:17 UTC, balesniy commented on src/components/room/room.jsx
>                <div className="property__description">
описание придет в данных

2021-02-17 14:17 UTC, balesniy commented on src/components/room/room.jsx
>                <h2 className="reviews__title">Reviews &middot; <span className="reviews__amount">{id + 1}</span></h2>
в reviews__amount нужно поставить количество отзывов

2021-02-19 12:44 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +  const onInputChange = (evt) => {
Исправлено

2021-02-19 12:47 UTC, Yougn commented on src/components/reviews-form/reviews-form.jsx
> +        {numbers.map((number)=> <Star key={number} id={number} userChoise={userChoise} onInputChange={onInputChange} />)}
Исправлено

2021-02-19 12:47 UTC, Yougn commented on src/components/room/near-room/near-room.jsx
> +  nearOffer: PropTypes.shape(propCard)
Исправлено

2021-02-19 12:51 UTC, Yougn commented on src/components/room/property-inside/property-inside.jsx
> +const PropertyInside = (props) => {
при мапинге добавляю список вещей в квартире

2021-02-19 13:05 UTC, Yougn commented on src/components/room/room.jsx
> +            <RoomPhoto img={img} />
Исправлено

2021-02-19 13:19 UTC, Yougn commented on src/components/room/room.jsx
>          <div className="property__container container">
Исправлено

2021-02-19 13:22 UTC, Yougn commented on src/components/room/room.jsx
>                <div className="property__description">
Исправлено

2021-02-19 13:23 UTC, Yougn commented on src/components/room/room.jsx
>                <h2 className="reviews__title">Reviews &middot; <span className="reviews__amount">{id + 1}</span></h2>
Исправлено

2021-02-19 22:35 UTC, balesniy approved these changes

2021-02-19 22:35 UTC, balesniy commented on package.json
> +    "css-loader": "^5.0.2",
версии зависимостей просят фиксировать

2021-02-19 22:35 UTC, balesniy commented on src/components/map/map.jsx
> +    const city = [52.38333, 4.9];
все данные компонент должен получить из пропс, в том числе и город

2021-02-19 22:35 UTC, merged

2021-02-20 11:49 UTC, Yougn commented on package.json
> +    "css-loader": "^5.0.2",
Исправлено

2021-02-20 12:02 UTC, Yougn commented on src/components/map/map.jsx
> +    const city = [52.38333, 4.9];
Исправлено