добавил карту
htmlacademy-react/1138711-six-cities-6 pull request #7
Opened 2021-02-20 12:36 UTC by Yougn

2021-02-20 22:43 UTC, balesniy requested changes

2021-02-20 22:43 UTC, balesniy commented on src/components/app/app.jsx
> +  city: PropTypes.array.isRequired,
нужно уточнить тип, массивы просят называть во множественном числе

2021-02-20 22:43 UTC, balesniy commented on src/components/main-board/main-board.jsx
> +  city: PropTypes.array.isRequired,
arrayOf

2021-02-20 22:43 UTC, balesniy commented on src/components/room/room.jsx
> +          <Map city={city} elements={nearOffers} />
> На карте отмечено не больше 3-х предложений неподалёку и маркер текущего предложения. Маркеры предложений выделены синим. Маркер текущего предложения выделен оранжевым.

2021-02-21 21:13 UTC, Yougn commented on src/components/room/room.jsx
> +          <Map city={city} elements={nearOffers} />
Исправлено

2021-02-21 21:17 UTC, Yougn commented on src/components/app/app.jsx
> +  city: PropTypes.array.isRequired,
city - дефолтные координаты центра города

2021-02-21 21:17 UTC, Yougn commented on src/components/main-board/main-board.jsx
> +  city: PropTypes.array.isRequired,
Исправлено

2021-02-22 14:59 UTC, balesniy commented on src/components/room/room.jsx
> +  city: PropTypes.array.isRequired,
PropTypes.arrayOf

2021-02-22 14:59 UTC, merged