подключил redux
htmlacademy-react/1138711-six-cities-6 pull request #8
Opened 2021-02-23 14:36 UTC by Yougn

2021-02-24 12:39 UTC, balesniy requested changes

2021-02-24 12:39 UTC, balesniy commented on src/components/app/app.jsx
> +          <MainBoard city ={city} />
текущий город нужно взять из компонента списка городов

2021-02-24 12:39 UTC, balesniy commented on src/components/cities-list/cities-list.jsx
> +      <li className="locations__item" onClick={choseCityName}>
элементы списка можно оформить в цикле

2021-02-24 12:39 UTC, balesniy commented on src/components/cities-list/cities-list.jsx
> +let mapDispatchToProps = (dispatch) => {
const

2021-02-24 12:39 UTC, balesniy commented on src/components/main-board/main-board.jsx
> +            <b className="places__found">{filteredOffers.length} places to stay in Amsterdam</b>
тут нужно отобразить название текущего города

2021-02-24 12:39 UTC, balesniy commented on src/components/main-board/main-board.jsx
>    offers: PropTypes.array.isRequired
нужно уточнить типы

2021-02-24 12:39 UTC, balesniy commented on src/components/main-board/main-board.jsx
> +let mapStateToProps = (state) => {
const

2021-02-24 12:39 UTC, balesniy commented on src/components/map/map.jsx
> +      container._leaflet_id = null;
такое решение приводит к переинициализации карты на каждой смене пропс, посмотри вариант в https://stackoverflow.com/questions/61705998/react-leaflet-hooks-setview-and-useref

2021-02-24 12:39 UTC, balesniy commented on src/components/sort-offers/sort-offers.jsx
> +    if (sortChoise === false) {
лишние условия

2021-02-24 12:39 UTC, balesniy commented on src/index.js
>  const city = [52.38333, 4.9];
текущий город придет из стора

2021-02-24 12:39 UTC, balesniy commented on src/index.js
> +        cardsCount={Setting.CARDS_COUNT}
кол-во карточек нужно посчитать для текущего города

2021-02-24 12:39 UTC, balesniy commented on src/redux/action.js
> +  FILL_OFFERS_LIST: `main-board/fillListOffers`,
не используется

2021-02-25 18:57 UTC, Yougn commented on src/components/map/map.jsx
> +      container._leaflet_id = null;
Исправлено

2021-02-25 19:55 UTC, Yougn commented on src/components/main-board/main-board.jsx
> +            <b className="places__found">{filteredOffers.length} places to stay in Amsterdam</b>
Исправлено

2021-02-25 19:58 UTC, Yougn commented on src/components/main-board/main-board.jsx
>    offers: PropTypes.array.isRequired
Исправлено

2021-02-25 19:59 UTC, Yougn commented on src/components/main-board/main-board.jsx
> +let mapStateToProps = (state) => {
Исправлено

2021-02-25 20:00 UTC, Yougn commented on src/components/sort-offers/sort-offers.jsx
> +    if (sortChoise === false) {
Исправлено

2021-02-25 20:52 UTC, Yougn commented on src/components/cities-list/cities-list.jsx
> +      <li className="locations__item" onClick={choseCityName}>
Исправлено

2021-02-25 21:13 UTC, Yougn commented on src/components/cities-list/cities-list.jsx
> +let mapDispatchToProps = (dispatch) => {
Исправлено

2021-02-25 21:16 UTC, Yougn commented on src/index.js
> +        cardsCount={Setting.CARDS_COUNT}
Исправлено

2021-02-26 12:33 UTC, Yougn commented on src/components/app/app.jsx
> +          <MainBoard city ={city} />
Исправлено

2021-02-26 12:36 UTC, Yougn commented on src/index.js
>  const city = [52.38333, 4.9];
Исправлено

2021-02-26 12:40 UTC, Yougn commented on src/redux/action.js
> +  FILL_OFFERS_LIST: `main-board/fillListOffers`,
Исправлено

2021-02-26 13:03 UTC, merged